### ISSUE TITLE
Dashboard Design anaylsis

### ISSUE THREAD

**Issue by joebu23** [digital-industry-group/Capstone2022#18]

**Comment by joebu23** [comment]
- Wireframe and/or actual design
- Write in whatever (by hand/SaaS/Vue.js dummy data)

**Comment by yuanlinhao** [comment]
The vue 3.0 and element-plus environment is set up and pushed to the front end repo, this is the first time I use element plus, so i still need to figure out what they provide and would be useful for our project. Also, would you mind invite professor Adams to our front end repo too? @joebu23
