### ISSUE TITLE
Pull Data from Google targeted search

### ISSUE THREAD

**Issue by joebu23** [digital-industry-group/Capstone2022#3]

**Comment by nunezjo** [comment]
- Insomnia requires a subscription of 5$ Monthly or 50$ Yearly.

**Comment by joebu23** [comment]
Insomnia does have a free version but if it's acting like a butt, use Postman instead (https://www.postman.com/)

**Comment by nunezjo** [comment]
Is Google AdWords currently being used for Paid Search Ads analytics? Another way to check Ads Analytics is within Google Analytics 4 -> Acquisition Overview -> Google Ads Campaigns -> Google Ads Keyword Text

**Comment by nunezjo** [comment]
Link Google Ads to Google Analytics
![image.png](https://images.zenhubusercontent.com/630e81455f07544a8ee43a65/b4781df4-8c80-4e83-b4b4-48286b78606f)

**Comment by nunezjo** [comment]
![image.png](https://images.zenhubusercontent.com/630e81455f07544a8ee43a65/b4781df4-8c80-4e83-b4b4-48286b78606f)

**Comment by nunezjo** [comment]
https://www.postman.com/api-evangelist/workspace/google/api/ccade20e-e44a-4bc0-ae8c-2873ad8383b2
https://medium.com/kinandcartacreated/google-authentication-with-postman-12943b63e76a

Google Cloud Console, OAuth2 Credentials
![image.png](https://images.zenhubusercontent.com/630e81455f07544a8ee43a65/dc86c175-a911-4a7f-a7e0-52fb11e2ff83)

**Comment by nunezjo** [comment]
https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js

Use for testing data requests: https://developers.google.com/oauthplayground

https://developers.google.com/analytics/devguides/reporting/core/v3/reference

optimizesmart.com/how-to-use-google-analytics-api-without-any-coding/#0-introduction-to-apis
