### ISSUE TITLE
Pull Data from Donorbox

### ISSUE THREAD

**Issue by joebu23** [digital-industry-group/Capstone2022#7]

**Comment by yuanlinhao** [comment]
https://api-docs.idonate.com/master/data_20181231.html?python#create

For iDonate, we will need to contact them and provide them the user's email for them to give us an apikey

**Comment by yuanlinhao** [comment]
![image](https://user-images.githubusercontent.com/39031403/192127491-78dedc6f-1569-42fa-a263-9d9332feb374.png)

**Comment by yuanlinhao** [comment]
seems like they require you to use zapier, which cost 17 dollars a month
